[Delivers #149494553] Front End - Upload Image
CloudAssessments/s3photoapp pull request #14
Opened 2017-08-01 17:40 UTC by jonajonlee

![image](https://user-images.githubusercontent.com/6760959/28838619-b790481a-76a5-11e7-959e-d738c3c9ec7d.png)

2017-08-01 19:22 UTC, Harrison-M requested changes
One comment, one small change.

2017-08-01 19:22 UTC, Harrison-M commented on apps/web-client/middleware/upload.js
> +module.exports = (req, res) => {
Needs license comment

2017-08-01 19:22 UTC, Harrison-M commented on apps/web-client/app.js
> +app.post('/photo', require('./middleware/upload'));
this isn't something that needs to change, but I usually don't think of end route code as "middleware"? I've always stored it in a folder called "routes" or something like that. Not sure it makes much of a difference, though, and it's technically correct.

2017-08-01 20:35 UTC, jonajonlee commented on apps/web-client/app.js
> +app.post('/photo', require('./middleware/upload'));
Ah you're right. Even the scaffolding puts them like that. In my old place, our middleware is where we put our `(req, res, next) => {...}` handlers. Just confused it. But it's not really applicable here.

In short, I'm changing these to routes

2017-08-02 02:31 UTC, Harrison-M requested changes
Just a licensing thing

2017-08-02 02:31 UTC, Harrison-M commented on apps/web-client/public/javascripts/fileselect.js
> +$(function() {
License comment

2017-08-02 06:19 UTC, sreimer15 approved these changes

2017-08-02 16:23 UTC, Harrison-M approved these changes

2017-08-02 16:23 UTC, merged