[Delivers #149494485] Filter Service - Action - Filter Photo
CloudAssessments/s3photoapp pull request #15
Opened 2017-08-02 21:51 UTC by jonajonlee

- added Photo-Filter microservice
- changed Photo-Storage Upload endpoint to take an image buffer

![s3photos-greyscalesample](https://user-images.githubusercontent.com/6760959/28896458-6255462e-7791-11e7-830f-57f4c17d7efa.gif)

2017-08-02 22:33 UTC, Harrison-M requested changes
These two things plus the gif error

2017-08-02 22:33 UTC, Harrison-M commented on apps/photo-filter/server.js
> +const app = require('express')();
Needs license

2017-08-02 22:33 UTC, Harrison-M commented on apps/photo-filter/server.js
> +  console.log(`Photo Storage API listening on http://localhost:${PORT}`);
s/Storage/Filter

2017-08-02 23:08 UTC, sreimer15 approved these changes
Besides Gif Issue it looks good to me

2017-08-03 15:35 UTC, jonajonlee commented on apps/photo-filter/server.js
> +const app = require('express')();
fixed

2017-08-03 17:59 UTC, Harrison-M approved these changes

2017-08-03 18:01 UTC, merged